config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :messages

  map.resources :categories

  map.resources :links, :collection => {:list => :get}

  map.resources :users

  map.resource :session

  map.resources :pages
  
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  
  map.view_page ':name', :controller => 'viewer', :action => 'show'

  map.root :controller => "viewer", :action => "show", :name => 'home'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_and_belongs_to_many :categories
  validates_presence_of :title
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :login_required, :except => [:list]
  # GET /links
  # GET /links.xml
  def index
    @links = Link.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end
  
  def list
    @categories = Category.find(:all, :order => 'title')
    get_page_metadata
  end

  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        flash[:notice] = 'Link was successfully created.'
        format.html { redirect_to(@link) }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        flash[:notice] = 'Link was successfully updated.'
        format.html { redirect_to(@link) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<p>
    <b>Url</b><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    	<b>Category</b><br />
      <%= f.collection_select :category_ids, Category.find(:all, :order => 'title'), :id, :title, {}, :multiple => true %>
    </p>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= error_messages_for :link %>

<% form_for(@link) do |f| %>

	<%= render :partial => 'form', :locals => {:f => f} %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Description</th>
  </tr>

<% for link in @links %>
  <tr>
    <td><%=h link.url %></td>
    <td><%=h link.title %></td>
    <td><%=h link.description %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New link', new_link_path %>

app/views/links/list.html.erb
<h1>Resources</h1>
<% for category in @categories %>	
  <% unless category.links.empty? %>
  	<h2><%=h category.title %></h2>
  	<p><%=h category.description %></p>
  	<ul>
  	  <% for link in category.links %>
  		  <li><%= link_to link.title, link.url %></li>
  	  <% end %>
  	</ul>
	<% end %>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= error_messages_for :link %>

<% form_for(@link) do |f| %>
	
	<%= render :partial => 'form', :locals => {:f => f} %>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p>
  <b>Url:</b>
  <%=h @link.url %>
</p>

<p>
  <b>Title:</b>
  <%=h @link.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @link.description %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>